# Generated by Django 5.1.7 on 2025-03-30 02:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('buildingName', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='unit_images/')),
                ('leaseStart', models.DateField()),
                ('leaseEnd', models.DateField()),
                ('monthlyRent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('isRentNegotiable', models.BooleanField(default=False)),
                ('datePosted', models.DateField()),
                ('numBedroomsAvailable', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('totalBedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('numBathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('washerAndDryerAvailable', models.BooleanField()),
                ('petsAllowed', models.BooleanField()),
                ('furnished', models.BooleanField()),
                ('parkingPass', models.BooleanField()),
                ('otherPresentHousemates', models.BooleanField()),
                ('available', models.BooleanField()),
                ('genderPreference', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Any')], default=3)),
                ('minAge', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('maxAge', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('studentsOnly', models.BooleanField(default=False)),
                ('numPeopleContacted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=3)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('leaseStart', models.DateField()),
                ('leaseEnd', models.DateField()),
                ('maxRent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pets', models.BooleanField(default=False)),
                ('parkingPass', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearcherSavedListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_searchers', to='api.listing')),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to='api.searcher')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='subletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='api.subletter'),
        ),
    ]
