# Generated by Django 5.1.7 on 2025-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_listing_dateposted_alter_listing_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='subletter',
        ),
        migrations.AddField(
            model_name='listing',
            name='subletter_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
