# Generated by Django 5.1.7 on 2025-03-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_listing_subletter_listing_subletter_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subletter',
        ),
    ]
